lint:
  actions_ci: false
  files_exist:
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .gitignore
    - assets/nf-core-spatialaxe_logo_light.png
    - docs/images/nf-core-spatialaxe_logo_dark.png
    - docs/images/nf-core-spatialaxe_logo_light.png
    - .github/PULL_REQUEST_TEMPLATE.md
nf_core_version: 4.0.3
repository_type: pipeline
template:
  author: Sameesh Kher, Dongze He, Florian Heyl
  description: A pipeline for spatialomics Xenium In Situ data.
  force: false
  is_nfcore: true
  name: spatialaxe
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
  version: 1.0.1dev
