# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "cellpose_baysor_import_segmentation"
description: |
  combine image-based segmentation approach with cellpose and integrate results from coordinate-based segmentation
  through baysor to run import-segmentation in micron coordinate space
keywords:
  - baysor
  - cellpose
  - baysor run
  - segmentation
  - xeniumranger import-segmentation
  - image-based segmentation
  - coordinate-based segmentation
  - transcript filtering
  - polygons
components:
  - cellpose
  - resolift
  - resize/tif
  - get/transcripts/coordinates
  - baysor/preprocess/transcripts
  - baysor/estimate/scale/factor
  - baysor/run
  - xeniumranger/import/segmentation
  - split/transcripts
  - convert/mask/uint32
  - extract/dapi
  - stardist
input:
  - ch_morphology_image:
      description: |
        path to the morphology.ome.tif file
        Structure: [ val(meta), path("path-to-morphology.ome.tif") ]
  - ch_bundle_path:
      description: |
        path to the xenium bundle
        Structure: [ val(meta), path("path-to-xenium-bundle") ]
  - ch_transcripts_parquet:
      description: |
        input parquet file from the xenium bundle
        Structure: [ val(meta), path("path-to-transcripts.parquet") ]
  - ch_config:
      description: |
        config file for the xenium baysor run (stored in assets/config/xenium.toml)
        Structure: [ path("path-to-xenium.toml") ]
output:
  - cells_mask:
      description: |
        cell segmentation mask generated by running Cellpose with the cpsam algorithm
        Structure: [ val(meta), path("*masks.tif") ]
  - cells_flows:
      description: |
        cell flows generated by running Cellpose with the cpsam algorithm
        Structure: [ val(meta), path("*flows.tif") ]
  - cells_cells:
      description: |
        cell segmentation mask as a numpy array generated by running Cellpose with the cpsam algorithm
        Structure: [ val(meta), path("*seg.npy") ]
  - nuclei_mask:
      description: |
        nuclei segmentation mask generated by running Cellpose with the nuclei algorithm
        Structure: [ val(meta), path("*masks.tif") ]
  - nuclei_flows:
      description: |
        nuclei flows generated by running Cellpose with the nuclei algorithm
        Structure: [ val(meta), path("*masks.tif") ]
  - nuclei_cells:
      description: |
        nuclei segmentation mask as a numpy array generated by running Cellpose with the nuclei algorithm
        Structure: [ val(meta), path("*seg.npy") ]
  - segmentation:
      description: |
        the segmentation.csv file generated from the baysor run command
        Structure: [ val(meta), path("*segmentation.csv") ]
  - polygons2d:
      description: |
        the segmentation_polygons_2d.json file generated from the baysor run command
        Structure: [ val(meta), path("*segmentation_polygons_2d.json") ]
  - coordinate_space:
      description: |
        the coordinate space in which xeniumranger import-segmentation was run
        Structure: [ val("microns") ]
  - redefined_bundle:
      description: |
        the redefined xenium bundle generated with the segmentation results from baysor
        Structure: [ val(meta), ["redefined-xenium-bundle"] ]
authors:
  - "@khersameesh24"
maintainers:
  - "@khersameesh24"
